name: deepmut
dependencies:
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - numpy=1.19.5
  - python=3.6.12
  - scikit-learn=0.23.2
  - conda-forge::biopandas=0.2.7
  - conda-forge::shortuuid=1.0.1
  - conda-forge::umap-learn=0.4.0
  - conda-forge::pynndescent=0.4.8
  - pip:
      - biopython==1.79
      - optuna==3.0.6
      - pandas==1.1.5
      - tensorflow==2.5.0
